sonar.projectKey=notes-app-hassan
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/coverage/**,**/build/**,**/dist/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info